apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: partitionjob
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: partitionjob
  name: partitionjobsvctoken
  namespace: partitionjob-system
  annotations:
    kubernetes.io/service-account.name: partitionjob-controller-manager