apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: partitionjobsvctoken
  namespace: partitionjob-system
  annotations:
    kubernetes.io/service-account.name: partitionjob-controller-manager