apiVersion: webapp.my.domain/v1
kind: PartitionJob
metadata:
  labels:
    app.kubernetes.io/name: partitionjob
    app.kubernetes.io/instance: partitionjob-sample
    app.kubernetes.io/part-of: partitionjob
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: partitionjob
  name: partitionjob-sample
spec:
  partitions: 1
  selector:
    matchLabels:
      app: for-partition
  template:
    spec:
      containers:
        - name: nginx-container
          image: nginx-alpine
