name: Go E2E Tests with Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prvalidation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.26.1/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Install kubeadm and kubelet
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubelet=1.26.1-00 kubeadm=1.26.1-00 kubectl=1.26.1-00
        sudo apt-mark hold kubelet kubeadm

    - name: Initialize Kubernetes cluster
      run: |
        sudo kubeadm init --kubernetes-version=v1.26.1 --pod-network-cidr=10.244.0.0/16  --timeoutForControlPlane=10m0s

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config


    - name: Build controller
      run: |
        make manifests
        make install
