name: PR validation for PartitionJob

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  PRvalidation:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0 

      - name: Run Unit Tests
        run: |
          make unit-test
      
      - name: Run controller
        run: |
          make manifests
          make install
          make run &

      - name: Run E2E Tests
        run: |
          make e2e-test
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
   
      - name: Run Docker Build
        run: |
          make docker-build IMG=1d3r3r/partitionjob:latest

      
      - name: Run Docker Push
        run: |
          make docker-push IMG=1d3r3r/partitionjob:latest

    # - name: Deploy
    #   run: |
    #     make deploy IMG=1d3r3r/partitionjob:latest

