name: PR validation for PartitionJob

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  PRvalidation:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: |
          go build
          if [[ $? -eq 0 ]]; then
            echo "Build succeeded"
          else
            echo "Build failed"
          fi

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0 

      - name: Run E2E tests
        run: |
          ./e2e-tests.sh
